name = "fastapi"
compatibility_date = "2024-06-09"

[vars]

UPSTASH_REDIS_REST_TOKEN="AfIYAAIjcDExZjk3YjE3ODBlMjU0NGQ1YWI4MmNiZDU4NzEzMTUyOHAxMA"
UPSTASH_REDIS_REST_URL="https://super-goat-61976.upstash.io"
